// AUTH

const LOGIN = "LOGIN";
const LOGOUT = "LOGOUT";
const SET_USER = "SET_USER";

// POSTS

const SET_POSTS = "SET_POSTS";
const CREATE_POST = "CREATE_POST";
const UPDATE_POST = "UPDATE_POST";
const DELETE_POST = "DELETE_POST";

export {
  // AUTH
  LOGIN,
  LOGOUT,
  SET_USER,
  // POSTS
  SET_POSTS,
  CREATE_POST,
  UPDATE_POST,
  DELETE_POST,
};
